name: Build and Publish Docker Image

on:
  workflow_dispatch:

env:
  PRIVATE_REPO: kubendoscope/hub
  IMAGE_NAME: hub

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: "KubeEndoscope Upload"

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PA_TOKEN }}  # Replace with your actual secret name

      - name: Clone private repository
        run: |
          git clone https://${{ github.actor }}:${{ secrets.PA_TOKEN }}@github.com/${{ env.PRIVATE_REPO }} private-repo
        shell: bash

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }} ./private-repo

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
